name: Render Keep Alive 5Mins

on:
  schedule:
    # 5분마다 실행 설정
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: |
          curl -I "https://talktalk-bot-o8dy.onrender.com"
